<a href="https://colab.research.google.com/github/SandaMaster/data-science/blob/master/ATENA__projket_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path = r"C:/Users/Grzegorz Mróz/Desktop/Projekt DS2.0/chatgpt-reddit-comments.csv"
csv = pd.read_csv(path)

In [ ]:
csv

Unnamed: 0 comment_id comment_parent_id  \
0              0    iztdxuh         t3_zj2aeu   
1              1    iztn0q0         t3_zj2aeu   
2              2    izudrph         t3_zj2aeu   
3              3    iztfhtb         t3_zj2aeu   
4              4    izu2as9         t3_zj2aeu   
...          ...        ...               ...   
52411      16668    j5m0v6m        t3_10jmvpj   
52412      16669    j5m6aj0        t1_j5m0v6m   
52413      16670    j5nylax        t1_j5m0v6m   
52414      16671    j5mwpdr        t1_j5m6aj0   
52415                  NaN               NaN   

                                            comment_body     subreddit  
0      I've been shocked for days now, I don't need c...     r/ChatGPT  
1       \n\nI am so angry right now. I just wasted my...     r/ChatGPT  
2      chatgpt karma whoring is here folks! just when...     r/ChatGPT  
3                                     Worked on me, ngl.     r/ChatGPT  
4      Certified 10/10, must-see moment. It really di...     r/ChatGPT  
...                                                  ...           ...  
52411             Read the T.O.S., you'll thank me later  r/technology  
52412  What am I missing here... https://openai.com/t...  r/technology  
52413            What does ChatGTP think of its own TOS?  r/technology  
52414  Don't know what they're referring to in the TO...  r/technology  
52415                                                NaN           NaN  

[52416 rows x 5 columns]

In [ ]:
comments = csv[["comment_id","comment_parent_id","comment_body"]]
comments

comment_id comment_parent_id  \
0        iztdxuh         t3_zj2aeu   
1        iztn0q0         t3_zj2aeu   
2        izudrph         t3_zj2aeu   
3        iztfhtb         t3_zj2aeu   
4        izu2as9         t3_zj2aeu   
...          ...               ...   
52411    j5m0v6m        t3_10jmvpj   
52412    j5m6aj0        t1_j5m0v6m   
52413    j5nylax        t1_j5m0v6m   
52414    j5mwpdr        t1_j5m6aj0   
52415        NaN               NaN   

                                            comment_body  
0      I've been shocked for days now, I don't need c...  
1       \n\nI am so angry right now. I just wasted my...  
2      chatgpt karma whoring is here folks! just when...  
3                                     Worked on me, ngl.  
4      Certified 10/10, must-see moment. It really di...  
...                                                  ...  
52411             Read the T.O.S., you'll thank me later  
52412  What am I missing here... https://openai.com/t...  
52413            What does ChatGTP think of its own TOS?  
52414  Don't know what they're referring to in the TO...  
52415                                                NaN  

[52416 rows x 3 columns]

In [ ]:
from cleantext import clean

Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.


In [ ]:
# segregacja i czyszczenie danych 
list_comment = []
clean_list_commnet = []

for comment_parent, comment_body in zip(comments["comment_parent_id"], comments["comment_body"]):
    part_data = str(comment_parent)+ ":\n" + str(comment_body) + "\n"
    clean_part_data = clean(part_data, no_emoji=True, no_urls=True)
    clean_part_data_ = clean_part_data + "\n"
    list_comment.append(part_data)
    clean_list_commnet.append(clean_part_data_)

In [ ]:
for x in clean_list_commnet[:100]:
    print(x)

t3_zj2aeu:
i've been shocked for days now, i don't need clickbait.

t3_zj2aeu:
i am so angry right now. i just wasted my time reading a post on this sub that had a clickbait title, and it was all because of chatgpt. i can't believe that this machine learning model was able to trick me into thinking that the post was interesting, when it was actually just a bunch of meaningless garbage.
i am so sick and tired of chatgpt and its ability to generate fake titles and content that is designed to trick people into clicking on them. this is not the first time that chatgpt has fooled me, and i am sure it won't be the last. but i am not going to stand for it anymore.
i demand that the moderators of this sub take action against chatgpt and its creators. we need to put a stop to this trickery, and we need to hold chatgpt accountable for the harm it is causing to this community. i am tired of being deceived by this machine, and i will not stand for it any longer.
so if you are reading this, chatgpt

In [ ]:
# zapisywanie danych do pilku .txt
to_write = "\n".join(clean_list_commnet)
f = open("reddit_text.txt", mode="w")
f.write(to_write)
f.close

<function TextIOWrapper.close()>

In [ ]:
path = "/net/people/plgrid/plgmrogrze/reddit_text.txt"
f = open(path)
data = f.read()
f.close
print(data)

FileNotFoundError: [Errno 2] No such file or directory: '/net/people/plgrid/plgmrogrze/reddit_text.txt'

In [ ]:
import tensorflow as tf
import numpy as np
import keras

In [ ]:
## tokenizowanie zanków
token = tf.keras.preprocessing.text.Tokenizer(char_level=True)
token.fit_on_texts([data])

In [ ]:
token.texts_to_sequences(["schocked"])

[[1, 2]]

In [ ]:
token.sequences_to_texts([[8, 14, 10, 5, 14, 25, 2, 12]])

['d']

In [ ]:
# całkowita liość tokenów 
max_chars = len(token.word_index)
max_chars

3

In [ ]:
dataset_size = token.document_count # iliść źródeł z jakich mamy dane 
dataset_size

1

In [ ]:
"".join(sorted(set(data.lower()))) # dodtakopwy kod pokayje wszyskie 68 znaków zamienionych na małe 

'dfs'

In [ ]:
# funkcjia ustawia domyślnie wyszkie litery na małe
text_vec_layer = tf.keras.layers.TextVectorization(split="character",
                                                   standardize="lower")
text_vec_layer.adapt([data])
encoded = text_vec_layer([data])[0]

In [ ]:
# wywalnie 0 tokenu i 1 - nieznanego
encoded -= 2  
n_tokens = text_vec_layer.vocabulary_size() - 2  
dataset_size = len(encoded)  

In [ ]:
n_tokens

3

In [ ]:
dataset_size

12

In [ ]:
def to_dataset(sequence, length, shuffle=False, seed=None, batch_size=32):
# mniejsze podzbiory z długiego tekstu, 200 znaków w jednym podzbiorze i przesunięcie o 1 znak    
    ds = tf.data.Dataset.from_tensor_slices(sequence)
    ds = ds.window(length + 1, shift=1, drop_remainder=True)
# przekształcanie podziorów do jednego wymiaru, płaskiego flat     
    ds = ds.flat_map(lambda window_ds: window_ds.batch(length + 1))
## teraz można przetasować i pogrupować (tam gadzie się kończy jeden zaczyna drugi)    
    if shuffle:
        ds = ds.shuffle(100_000, seed=seed)
    ds = ds.batch(batch_size)
    return ds.map(lambda window: (window[:, :-1], window[:, 1:])).prefetch(1)

##### Tworzenie zbiorów 

In [ ]:
# pokazuje w którym miejscu zaczynją się nowe tokeny wyrazów 
list(to_dataset(text_vec_layer(["ve been"])[0], length=4))

[(<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
  array([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]], dtype=int64)>,
  <tf.Tensor: shape=(3, 4), dtype=int64, numpy=
  array([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]], dtype=int64)>)]

In [ ]:
# ilość słow w ramce 200 i 90% zb train
length = 200
tf.random.set_seed(42)
train_set = to_dataset(encoded[:11_141_203], length=length, shuffle=True,
                       seed=42)
valid_set = to_dataset(encoded[11_141_203:11_760_158], length=length)
test_set = to_dataset(encoded[11_760_158:], length=length)

##### Sieć i ternowanie 

In [ ]:
from keras import Sequential
from keras import layers

In [ ]:
network = Sequential()
network.add(layers.Embedding(input_dim=max_chars, output_dim=16))
network.add(layers.GRU(256, return_sequences=True, dropout=0.2, recurrent_dropout=0.2))
network.add(layers.GRU(128, return_sequences=True, dropout=0.2, recurrent_dropout=0.2))
network.add(layers.GRU(68, return_sequences=True, dropout=0.2, recurrent_dropout=0.2))
network.add(layers.Dense(max_chars, activation="softmax")) 

In [ ]:
network.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])

In [ ]:
## po wytrenoawnaiu modelu można dostarczyć do niego tekst
def preprocess(text):
    X = np.array(token.texts_to_sequences(text)) -1
    return tf.one_hot(X, max_chars)

In [ ]:
# prognozowanie litery w jakimś tekscie 
x_new = preprocess(['Hi how are yo'])
y_pred = network.predict_classes(x_new)
token.sequences_to_texts(y_pred +1)[0][-1] # pierwsze zdanie ostatni znak

NameError: name 'model' is not defined