In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.Series([0.2,0.32,0.12])
data

0    0.20
1    0.32
2    0.12
dtype: float64

In [4]:
print(data.index)
print(data.values)

RangeIndex(start=0, stop=3, step=1)
[0.2  0.32 0.12]


In [10]:
data = pd.Series([0.2,0.32,0.12], index = ['s','f','h'])
data

s    0.20
f    0.32
h    0.12
dtype: float64

In [11]:
data['f']

0.32

In [33]:
popalution_dict = {
    'Krakow':123123,
    'California':32321312,
    'Warszawa': 6746234,
    'New York': 65423443,
    'Sosnowiec':-1,
}

popalution_dict

{'Krakow': 123123,
 'California': 32321312,
 'Warszawa': 6746234,
 'New York': 65423443,
 'Sosnowiec': -1}

In [34]:
popalution = pd.Series(popalution_dict)
popalution

Krakow          123123
California    32321312
Warszawa       6746234
New York      65423443
Sosnowiec           -1
dtype: int64

In [35]:
popalution['Sosnowiec']


-1

In [36]:
popalution['California': 'New York']

California    32321312
Warszawa       6746234
New York      65423443
dtype: int64

In [47]:
series = [
    pd.Series([2,3,4]),
    pd.Series(5, index=[1,2,3]),
    pd.Series({2:'a',4:'d',8:'f'}),
    pd.Series(np.arange(10), index =np.arange(10,20))
]
series

[0    2
 1    3
 2    4
 dtype: int64,
 1    5
 2    5
 3    5
 dtype: int64,
 2    a
 4    d
 8    f
 dtype: object,
 10    0
 11    1
 12    2
 13    3
 14    4
 15    5
 16    6
 17    7
 18    8
 19    9
 dtype: int32]

In [48]:
for i in series:
    print(i)

0    2
1    3
2    4
dtype: int64
1    5
2    5
3    5
dtype: int64
2    a
4    d
8    f
dtype: object
10    0
11    1
12    2
13    3
14    4
15    5
16    6
17    7
18    8
19    9
dtype: int32


### Data Frame

In [51]:
area_dict={
    'Krakow':2131,
    'California':231232,
    'New York':786324,
    'Illonis':4234,
}

area = pd.Series(area_dict)
area

Krakow          2131
California    231232
New York      786324
Illonis         4234
dtype: int64

In [54]:
state = pd.DataFrame({'population':popalution,
                     'area':area})
state

population      area
California  32321312.0  231232.0
Illonis            NaN    4234.0
Krakow        123123.0    2131.0
New York    65423443.0  786324.0
Sosnowiec         -1.0       NaN
Warszawa     6746234.0       NaN

In [56]:
state.index

Index(['California', 'Illonis', 'Krakow', 'New York', 'Sosnowiec', 'Warszawa'], dtype='object')

In [58]:
state.columns

Index(['population', 'area'], dtype='object')

In [60]:
state[['population','area']]

population      area
California  32321312.0  231232.0
Illonis            NaN    4234.0
Krakow        123123.0    2131.0
New York    65423443.0  786324.0
Sosnowiec         -1.0       NaN
Warszawa     6746234.0       NaN

In [61]:
state[['population']]

population
California  32321312.0
Illonis            NaN
Krakow        123123.0
New York    65423443.0
Sosnowiec         -1.0
Warszawa     6746234.0

In [62]:
data = [{'a':i,'b':2*i}for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [66]:
dfs = [
    pd.DataFrame(popalution, columns=['population']),
    pd.DataFrame(data),
    pd.DataFrame([{'a':1,'b':2},
                {'b':3,'c':4}]),
    pd.DataFrame({'population':popalution,
                     'area':area}),
    pd.DataFrame(np.random.rand(3,2),
                columns =['foo','bar'],
                index = ['a','b','c'])
    
]

for i in dfs:
    print(i)

            population
Krakow          123123
California    32321312
Warszawa       6746234
New York      65423443
Sosnowiec           -1
   a  b
0  0  0
1  1  2
2  2  4
     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0
            population      area
California  32321312.0  231232.0
Illonis            NaN    4234.0
Krakow        123123.0    2131.0
New York    65423443.0  786324.0
Sosnowiec         -1.0       NaN
Warszawa     6746234.0       NaN
        foo       bar
a  0.665249  0.273167
b  0.682448  0.784731
c  0.384677  0.518954


### Index


In [67]:
dfs[0].index

Index(['Krakow', 'California', 'Warszawa', 'New York', 'Sosnowiec'], dtype='object')

In [68]:
ind = pd.Index([2,3,4,5,6])
ind

Int64Index([2, 3, 4, 5, 6], dtype='int64')

In [70]:
a = np.array([1,2,3])
a[0]=3
a

array([3, 2, 3])

In [72]:
ind[1]=3 # w index nie mozna zmieniac wartości

TypeError: Index does not support mutable operations

## Indeskowanie i wybieranie danych


In [75]:
data = pd.Series(['s','b','c'], index = [1,3,5])
data


1    s
3    b
5    c
dtype: object

In [76]:
data[1] # index typu Series

's'

In [79]:
data[1:3] #index  z numpy

3    b
5    c
dtype: object

In [80]:
#loc, iloc

data.loc[1]

's'

In [81]:
data.loc[1:3]

1    s
3    b
dtype: object

In [82]:
data.iloc[1]

'b'

In [83]:
data.iloc[1:3]

3    b
5    c
dtype: object

## wybieranie danych z DataFrame

In [84]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [85]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [87]:
data['density'] = data['pop']/data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [88]:
data['pop']*2

California    76665042
Texas         52896386
New York      39302254
Florida       39105720
Illinois      25764270
Name: pop, dtype: int64

In [90]:
data['density'] = (data['pop']/data['area']).round(2)
data


area       pop  density
California  423967  38332521    90.41
Texas       695662  26448193    38.02
New York    141297  19651127   139.08
Florida     170312  19552860   114.81
Illinois    149995  12882135    85.88

In [91]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [93]:
data.loc[:'Texas',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193

In [94]:
data.density >100

California    False
Texas         False
New York       True
Florida        True
Illinois      False
Name: density, dtype: bool

In [95]:
data.loc[data.density >100]

area       pop  density
New York  141297  19651127   139.08
Florida   170312  19552860   114.81

In [97]:
data.loc[data.density >100, ['pop','density']]

pop  density
New York  19651127   139.08
Florida   19552860   114.81

In [98]:
data.iloc[0,2]=90

In [99]:
data

area       pop  density
California  423967  38332521    90.00
Texas       695662  26448193    38.02
New York    141297  19651127   139.08
Florida     170312  19552860   114.81
Illinois    149995  12882135    85.88

In [100]:
data.loc['California','density']=66
data

area       pop  density
California  423967  38332521    66.00
Texas       695662  26448193    38.02
New York    141297  19651127   139.08
Florida     170312  19552860   114.81
Illinois    149995  12882135    85.88

# Operowanie na brakujących danych 

In [103]:
vals1 = np.array([1,2,None,4])
vals1

array([1, 2, None, 4], dtype=object)

In [106]:
type(None)

NoneType

In [108]:
for dtype in ['object','int']:
    print(f"dtype={dtype}")
    %timeit np.array(1E6, dtype=dtype).sum()
    print()

dtype=object
1.72 µs ± 61.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

dtype=int
1.72 µs ± 40.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)



In [112]:
type(np.nan) #nan nie jest lizcba ale mozna robic operacje jak na liczbach

float

In [113]:
1 + np.nan

nan

In [115]:
vals2 = np.array([1,np.nan,2,3])
vals2.dtype

dtype('float64')

In [116]:
np.nansum(vals2)

6.0

In [125]:
a = pd.Series([1,2,np.nan,None,5])
a

0    1.0
1    2.0
2    NaN
3    NaN
4    5.0
dtype: float64

In [126]:
a.sum()

8.0

In [127]:
a.isnull() #znajdowanie pustych wartosci

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [128]:
a[a.isnull()] #wybieranie nie pustych wartości**

2   NaN
3   NaN
dtype: float64

In [130]:
a.dropna() #To lepsze niz a[a.isnull()] xD

0    1.0
1    2.0
4    5.0
dtype: float64

In [132]:
 area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': None,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data


area         pop
California  423967  38332521.0
Texas       695662         NaN
New York    141297  19651127.0
Florida     170312  19552860.0
Illinois    149995  12882135.0

In [136]:
data[data['pop'].notnull()]

area         pop
California  423967  38332521.0
New York    141297  19651127.0
Florida     170312  19552860.0
Illinois    149995  12882135.0

# łaczenie DataFrame


In [139]:
pd.concat?

In [141]:
ser1=pd.Series(['a','b','c'], index =[1,2,3])
ser2=pd.Series(['f','g','h'], index =[6,4,5])

In [142]:
pd.concat([ser1, ser2])

1    a
2    b
3    c
6    f
4    g
5    h
dtype: object

In [145]:
def make_df(cols,ind):#łaczenie kolum i wierszy np: A0, B1, C2
    data = {c:[str(c)+str(i) for i in ind]for c in cols} #<-- digit comprehantion
    return pd.DataFrame(data,ind)
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [157]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])

df1, df2

(    A   B
 1  A1  B1
 2  A2  B2,
     A   B
 3  A3  B3
 4  A4  B4)

In [154]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [155]:
a=pd.concat([df1,df2], axis=1)
a

A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

In [153]:
a['A']

A    A
1   A1  NaN
2   A2  NaN
3  NaN   A3
4  NaN   A4

In [158]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

# SQL Joiny